#!/bin/bash

# Actual bashrc file is in XDG_CONFIG_HOME

# Don't do anything if not launched interactively
[[ -z "$PS1" ]] && return

XDG_BASHRC="$XDG_CONFIG_HOME/bash/bashrc"

[[ -f "$XDG_BASHRC" ]] && source "$XDG_BASHRC"
